[package]
name = "roslaunchd"
version = "0.1.0"
authors = ["Lucas Chiesa <lucas.chiesa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
